{"name": "При авторизации под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "start": 1725227771473, "stop": 1725227772581, "uuid": "f535a621-580d-44a4-a463-ea5e06d86fe8", "historyId": "24f77987944a3c3d8700d6323d3528e3", "testCaseId": "24f77987944a3c3d8700d6323d3528e3", "fullName": "tests.test_login_courier.TestLogiEndpoints#test_unknown_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLogiEndpoints"}, {"name": "host", "value": "Notebook"}, {"name": "thread", "value": "9016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}